# Database
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/cheesedb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

# Multipart
spring.servlet.multipart.location=C:\\cheese\\Cheese\\tmp
spring.servlet.multipart.max-file-size=104857600
spring.servlet.multipart.max-request-size=104857600
spring.servlet.multipart.file-size-threshold=0

# Redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=1234567890

# Token
cheese.access-token.prefix=ACCESS_TOKEN:
cheese.refresh-token.prefix=REFRESH_TOKEN:
cheese.access-token.expiration=600
cheese.refresh-token.expiration=600
cheese.black-list.value=logout

# Manager
cheese.manager-file.location=C:\\cheese\\Cheese\\manager.txt
cheese.manager-email=manager@cheese.com

# BranchCost
cheese.shooting-cost=1000
cheese.printing-cost=2000